atomicals/atomicals-electrumx

electrumx/server/block_processor.py
electrumx/server/db.py
electrumx/server/session.py

Fix commit
Fix locations array to be limited for now
Start adding dft info

Fix locations

---

electrumx/lib/util_atomicals.py
electrumx/server/block_processor.py
electrumx/server/db.py
electrumx/server/session.py

- Mint with bitworkc and bitworkr

Additional subrealm minting capabilities

---

electrumx/server/block_processor.py

A reorg occurred on BTC in the past day and resulted in the indexer to crash.
The problem was the decrement of the `m` of the atomicals undo information was in the wrong place and resulted in an overflow of the value and triggered the assert.
The check for the `m` value was moved to the correct location and fixes the error.

Fix logic for reorg incorrectly counting atomical undo info

---

electrumx/server/db.py
electrumx/server/session.py

Add an rpc call to get the atomical number to atomical id mapping. Usefull for debugging and listing the atomicals by number.
Sample response:
```
{
"success": true,
"response": {
"global": {
"coin": "Bitcoin",
"network": "mainnet",
"height": 820321,
"block_tip": "0000000000000000000091dc7854529a8b3848adef571c124583f96d966015aa",
"server_time": "2023-12-08T22:34:35.123423",
"atomicals_block_tip": "a2e33694f24e77ac32bb024393252b9da2f480e47cbdfe01b41fc9e616cf4dda",
"atomical_count": 133876,
"atomicals_block_hashes": {
"820312": "495db8a2404553b5100401fa90ad59de659ae27b1d82e4068dfc1e4c0014b949",
"820313": "416fc8dd8fb37b3b004ec5a2c24b96bc9249620e2ef242cdee261536be52744c",
"820314": "9810d870e75321cced69d56da5552f01c707894777113de29d1d84a3b74d5c80",
"820315": …
```

Add blockchain.atomicals.num_to_id rpc call

---

electrumx/server/block_processor.py
electrumx/server/db.py
electrumx/server/session.py

Requires resync of db from height 808080

Add default exponent=0 to prepare for token substantiation

---

electrumx/lib/util_atomicals.py
electrumx/server/block_processor.py

Fixes a problem with split handling for validation and also now denies allowing split to be used when paying for subrealms or dmitems.

Fix split handling

---

electrumx/lib/util_atomicals.py
electrumx/server/block_processor.py
electrumx/server/session.py

Add performance improvements by caching the DFT/FT info lookup

Add performance improvements by caching the DFT/FT info lookup

---

electrumx/server/block_processor.py

Fixes exception when invalid commit_index is used.

Fix commit_index log error

---

electrumx/lib/script2addr.py
tests/lib/test_script2addr.py

support btc network ： mainnet ,testnet,regtest
address type ：p2pkh,p2sh,segwit address (version 0),segwit address (version 1-16)

support get_address_from_output_script

---

electrumx/server/http_middleware.py

use base64,fix_http_bytes_object_convert

---

electrumx/server/http_middleware.py
electrumx/server/session.py

Fix self.env bug
Fix import base64 error bug
Add post get_dft_mints method

bugfix: fix env and import base64

---

electrumx/server/http_session.py
electrumx/server/session.py

fix #92 get wrong ft/nft balance.

---

electrumx/server/db.py
electrumx/server/http_session.py
electrumx/server/session.py

Fix querying with `find_subrealms`

Fix query sub items

---

electrumx/server/http_session.py
electrumx/server/session.py

Addresses https://github.com/atomicals/atomicals-electrumx/issues/126#issuecomment-1978553911

⏪️ `is_verified_only=False`

---

electrumx/server/block_processor.py

They are only displayed when the item is verified. There is no need for the filtering.

⚡️ Returns parents for all sub-item

---

.github/workflows/tests.yml
electrumx/server/controller.py
electrumx/server/daemon.py
electrumx/server/env.py
tests/server/test_daemon.py

Continue with #147
Somehow help with syncing behind the wall.

✨ Support Daemon proxy

---

requirements.txt
setup.py

make rocksdb requirement optional

---

electrumx_server

🚸 Configurable `LOG_LEVEL` with `.env`

---

electrumx/server/http_middleware.py
electrumx/server/session.py

1. Add request logs for `SessionBase` (WebSocket requests).
2. Add params in the logs of HTTP requests.
3. Logs are logging with `DEBUG` level.

🔊  Improve handler logs

---

electrumx/server/block_processor.py

New blocks and reorg happen quickly on the testnet at this moment. Adding the semaphore may help to prevent flush assertions with these behaviors coming across each other or stacked.
```console
2024-04-27 06:47:14,089INFO:Prefetcher:new block height 2,732,855 hash 000000000000fd2f86b741b95c9de6a4be7bcc896f6278ffc2d34fbe68c706b5
2024-04-27 06:47:14,136INFO:BlockProcessor:chain reorg detected
2024-04-27 06:47:14,137INFO:Prefetcher:cancelled; prefetcher stopping
2024-04-27 06:47:14,147INFO:Controller:shutting down
2024-04-27 06:47:14,147INFO:Controller:shutdown complete
2024-04-27 06:47:14,157ERROR:electrumx:ElectrumX server terminated abnormally
Traceback (most recent call last):
File "/data/atomicals-electrumx/electrumx_server", line 48, in main
asyncio.run(controller.run())
File …
```

⚡️ Add semaphore for chain reorg action

---

electrumx/server/session/session_manager.py

Example:
An example of partial color ft merging. txid: `3643dc661ab39c09fd43b1ebaf30cda9daab962a684a3a52e6513950fe4f5cee` in Testnet3
```
{
"success": true,
"response": {
"txid": "3643dc661ab39c09fd43b1ebaf30cda9daab962a684a3a52e6513950fe4f5cee",
"height": 2819726,
"tx_num": 140835336,
"info": {},
"transfers": {
"inputs": {
"1": [
{
"address": "tb1pvcstpedmyalhw240duwpe797v8r7qqkv0r3agusnp2afpug4k63ssph5rl",
"atomical_id": "595522d778ec1f40e3068553ef5aef0ccb52c502786496c0882bb79818fa6db2i0",
"type": "FT",
"index": 1,
"value": 546
}
],
"2": [
{
"address": "tb1pvcstpedmyalhw240duwpe797v8r7qqkv0r3agusnp2afpug4k63ssph5rl",
"atomical_id": "595522d778ec1f40e3068553ef5aef0ccb52c502786496c0882bb79818fa6db2i0",
"type": "FT",
"index": 2,
"value": 1000
}
]
},
"outputs": {
"0": [
{
"address": …
```

Fix the issue with the value display in the transaction interface.
