atomicals/atomicals-electrumx

electrumx/lib/util_atomicals.py

Fix [this issue](https://github.com/atomicals/atomicals-electrumx/issues/12)

Fix: invalid argument to function sha256() results in TypeError: object supporting the buffer API required

---

electrumx/server/block_processor.py
electrumx/server/db.py

Correctly retrieve sealed status from db and the temporary cache used during a full sync.
If this change is not made, then a container may appear not sealed and therefore any subsequent dmint attempts would be considered invalid and therefore corrupt the index.

Fix fetching sealed status during resync when using cache before flush to db

---

electrumx/lib/coins.py
electrumx/server/block_processor.py

Update to prevent decentralized mints of FTs to re-use the bitwork proof of work for more than 1 output.
See example tx: https://mempool.space/tx/0000000094369b09906594d7fa037c45181357031ffbe5bd075dac72d39a3cfd
The tx above performs the bitwork once and many reveals are used to reuse the bitwork.
This patch makes it so only one output can claim the mint for the bitwork

Prevent decentralized mint from reusing bitwork for more than one output

---

electrumx/server/block_processor.py

Fixes crash on reorg when reverting the `b'th'` records for atomical txs per block

Correctly backup th on reorg

---

electrumx/lib/segwit_addr.py
electrumx/lib/util_atomicals.py
electrumx/server/db.py
electrumx/server/session.py
requirements.txt

Add a new api `blockchain.atomicals.get_atomical_holder`, it can receive three params. atomical_id, limit(default 100), offset(default 0). for example, if you want get 'avm' token holders. you can send by following curl command.
```
curl -X POST http://0.0.0.0:8080/proxy/blockchain.atomicals.get_atomical_holder -d '{"params":["d4c48c4db504282e987776cba26f78fbc1573460a02c45d9e5de37c5b13ef751i0", 3, 0]}' -H "Content-Type: application/json" | jq
```
will return:
```
{
"success": true,
"response": [
{
"percent": 0.01019047619047619,
"address": "bc1pf70gkj3zcxqmq4v3cjjngnpalhajnsc8fld9wl9xq547pvqgqmmqjw6j2f",
"holding": 214000
},
{
"percent": 0.008952380952380953,
"address": "bc1px95q3n0e39np6slcdxyy5rjr6erm54zk340wq45fxh5sg7skzq8q804wpj",
"holding": 188000
},
{
"percent": …
```

feat:add get holders by atomical_id

---

electrumx/lib/util_atomicals.py

In the old code, if you set `# NET=testnet` in config, the code couldn't get the NET var , the function will exception and return ''

fix get os env net error cause the function return none

---

electrumx/server/http_session.py
electrumx/server/session.py

In the two previous merges, there was an oversight in my commits. I removed the existing `get_address_from_output_script method`, but I overlooked the import error in the committed `http-session`. I have now fixed this issue and also removed the `banner` method because it caused errors during testing. I will continue to maintain `http-session.

fix import error and remove banner function

---

electrumx/server/block_processor.py
electrumx/server/session.py

This is the improvement that applies to all general caches by avoiding using `[]` (`__getitem__`) to get rid of possible `KeyError` which might cause the block processor offline. The request improves the fallback ability when the cache is missing too. Also a continuation of https://github.com/atomicals/atomicals-electrumx/pull/67/commits/b287b2732cd74c6f06eb7258af551051f065c484.
cc @shadowv0vshadow would appreciate your review too!

⚡️ Improve cache usages

---

requirements.txt

`del self.table` could cause unexpected exception in multi-threading operations. The request updates the `pylru` instead of manipulating the project to fix the problem. Using a fixed ref to avoid dependency breakage in the future.
See https://github.com/atomicals-community/pylru/compare/master...atomicals-community:pylru:fix/del-key-from-table for the details.

Use a fixed `pylru` with to avoid key deletion exceptions

---

electrumx/server/http_middleware.py
electrumx/server/session.py

- Set CORS headers for the application.
- Unify responses in handlers.
FYI @shadowv0vshadow

🐛 Allow CORS for HTTP protocol

---

electrumx/server/block_processor.py
electrumx/server/http_session.py
electrumx/server/session.py

fix holders percent error
And fix MINT_SUBNAME_RULES_BECOME_EFFECTIVE_IN_BLOCKS import error

fix perpetual holder error and constant import

---

electrumx/server/block_processor.py

Please correct me if I misunderstand anything here.
In the previous implementation, if non-leading candidates made payments but their previous candidates did not, the `verify` status would be returned incorrectly, between the revealed and the confirmed window.
Introducing `competing` for non-leading candidates. When a subrealm/dmint payment is in the window of [4, 15], their payment will be treated as competing, as they are waiting for their previous candidates to pay for the item.
Candidates [*A*, *B*], *B* made the payment at the 4th block before *A*.
Before:
- A: `pending_awaiting_payment`
- B: `verified`
After:
- A: `pending_awaiting_payment`
- B: `competing`
- Introduce `competing` status for payment candidates that are not the leading.
- Readable commit height diff.
- Remove …

🐛 Fix non-leading candidates payment status

---

electrumx/lib/util_atomicals.py
electrumx/server/block_processor.py

- Returns `pending_by_other` if leading candidates (compared to the current) have already paid which means the current candidate cannot win the item.
- Fixes the usage before declaration.
- Enriches notes.
- Fixes the incorrect log in the `get_effective_subrealm`.

⚡️ Improve `get_subname_request_candidate_status`

---

electrumx_server

Fix https://github.com/atomicals/atomicals-electrumx/issues/119
use watchedfilehandler instead,logs can still be record in the same file even the file is changed or moved https://docs.python.org/3/library/logging.handlers.html#watchedfilehandler

Fix #119 Log file can not be rotate daily without restarting

---

electrumx/lib/util_atomicals.py
tests/lib/test_get_subname_request_candidate_status.py

1. Fixes when the realm owner is minting its subrealm without following the rules, `invalid_request_no_matched_applicable_rule` will returned before it gets confirmed.
2. Reverts the problem when the block is still in the window of reveal delay, caused by #122.
3. Fixes corresponding tests.

🐛 Fix `get_subname_request_candidate_status`

---

electrumx/server/db.py

https://github.com/atomicals/atomicals-electrumx/commit/9fea1e7604125c9fa78909a19d4ff5201f721d7c  will crash with
```
"message": "'utf-8' codec can't decode byte 0x88 in position 11: invalid start byte"
```

fix name_len error

---

electrumx/server/block_processor.py
electrumx/server/http_session.py

The error `self.session_mgr.bp.general_data_cache[b'rtx' + hex_str_to_hash(prev_txid)] = prev_raw_tx` will cause crash

Fix get transaction detail bug

---

electrumx/server/http_session.py
electrumx/server/session.py

And add is_cleanly_assigned into res struct

Change transaction struct [Change inputs output to list]

---

requirements.txt

This truly enables RocksDB as a DB provider. (Tested on macOS)

➕ Adds RocksDB binding dependencies

---

electrumx/server/http_session.py
electrumx/server/session.py

Bytes data in the payload were not encoded correctly, which will throw with exception for WebSocket protocol (also with HTTP, but it has a middleware that implicitly handles these cases)

🐛 Fix transaction content format before returned to the call

---

electrumx/lib/atomicals_blueprint_builder.py
electrumx/server/block_processor.py
electrumx/server/http_session.py
electrumx/server/session.py

Fix burn and Fix transaction_by_scripthash function

---

electrumx_compact_history
electrumx_rpc
electrumx_server
requirements.txt

You don't need to run `source .env` manually and the server can be debugged easily.

🚸 Add `python-dotenv` to automatically load environments

---

electrumx/server/session.py

Histories are changed due to blocks. Clearing all caches will result in correct & accurate histories.

⚡️ Clear all history caches when block height changed

---

electrumx/server/http_session.py
electrumx/server/session.py

- Avoid extra `bump_cost` when making duplicate subscriptions.
- Define the missing `subscribe_headers` for the HTTP session, which recovers the functionality.

⚡️ Improve subscribe headers

---

electrumx/server/http_session.py
electrumx/server/session.py

In some case:
Transaction_detail will return error atomical_id, Because one location UTXO include multiple atomicals. We must got the last one atomical_id of the location when we do a `mint` operation.
Example:
```
curl -X POST http://example.com/proxy/blockchain.atomicals.transaction -d '{"params":["367314ee57a2b68c79a3c16e32e6036901db3a59f76652aefd21a0990d01e47b"]}'
```
```
{
"success": true,
"response": {
"op": "mint-nft-subrealm",
"txid": "367314ee57a2b68c79a3c16e32e6036901db3a59f76652aefd21a0990d01e47b",
"height": 2579801,
"tx_num": 72420140,
"info": {
"atomical_id": "8888f4bd2773505211874d437c92f003224316a782386a0f38ccedf1ad1c9d39i0",   // this atomical must be f6325c93960c39f1bdbda35a66f0cd0688ebc8319b5bed71d2403fc40ef6bacai0
"location_id": …
```

Fix transaction return error atomical_id

---

electrumx/lib/util_atomicals.py
electrumx/server/block_processor.py
electrumx/server/http_session.py
requirements.txt
setup.py

In testnet block processor,  We found some invalid payload.
```
...  File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
return future.result()
^^^^^^^^^^^^^^^
File "/Users/Documents/atomicals-electrumx/electrumx/lib/server_base.py", line 129, in run
await server_task
File "/Users/Documents/atomicals-electrumx/electrumx/lib/server_base.py", line 102, in serve
await self.serve(shutdown_event)
File "/Users/Documents/atomicals-electrumx/electrumx/server/controller.py", line 134, in serve
async with OldTaskGroup() as group:
File "/Users/Documents/atomicals-electrumx/venv/lib/python3.12/site-packages/aiorpcx/curio.py", line 297, in aexit
await self.join()
File …
```

fix CBORTag

---

.github/workflows/tests.yml
electrumx/lib/util_atomicals.py
electrumx/server/block_processor.py

<summary>JSON:</summary>
```json
{
"success": false,
"code": 800422,
"message": "the transaction was rejected by atomicals rules.\n\ndetected invalid ft token inputs and outputs for tx_hash=16b599f30d01200c9ef4ffec369228f1acd792c91fcd7b527acecdad94297f23, operations_found_at_inputs=None, atomicals_spent_at_inputs={0: [{'atomical_id': '553938581a2245774c983647df2dce811229a37ca5489a5d606348bb78f60a23i0', 'location_id': 'd0346994464fd8f52c29ae516a3a853fbe7f9313055d64d3952caa375ef4f490i0', 'data': '0375ae7496f0c9d79341fd66f6348a32308a28ef821b533ba9f12049766bc30c157b043e280a9b3a821d78e80300000000000000009c68210400', 'data_ex': {'value': 1000, 'exponent': 0}}, {'atomical_id': '5380036df841b472109174391bca9ce46a3238217fdb7111fdf2f5127356c98ci0', 'location_id': …
```

🚸 Produce readable `AtomicalsValidationError`

---

electrumx_server

The PR #171 made `electrumx_server` read `LOG_LEVEL` from env.
Previously we could use lowercase `info` because it would automatically convert to uppercase `INFO`. https://github.com/atomicals/atomicals-electrumx/blob/dd15e23099812e21894e46d76d5de0e897bc1d5d/electrumx/server/env.py#L73.
When upgrading our RPC endpoint (https://ep.nextdao.xyz/proxy/health) to v1.4.0, it started failed.

make LOG_LEVEL env compatible

---

electrumx/server/http_session.py
electrumx/server/session.py

Adds the ability to query specific block hash.

✨ `blockchain.atomicals.get_block_hash`

---

electrumx/server/http_session.py

Endpoints like `get_global` does not require any parameters. If the payload is empty, exceptions will be thrown.

🐛 Do not parse empty HTTP payload

---

.github/workflows/tests.yml
electrumx/server/history.py
tests/server/test_compaction.py

```console
Traceback (most recent call last):
File "/data/atomicals-electrumx/electrumx_server", line 47, in main
asyncio.run(controller.run())
File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
return future.result()
File "/data/atomicals-electrumx/electrumx/lib/server_base.py", line 129, in run
await server_task
File "/data/atomicals-electrumx/electrumx/lib/server_base.py", line 102, in serve
await self.serve(shutdown_event)
File "/data/atomicals-electrumx/electrumx/server/controller.py", line 134, in serve
async with OldTaskGroup() as group:
File "/usr/local/lib/python3.10/dist-packages/aiorpcX-0.22.1-py3.10.egg/aiorpcx/curio.py", line 297, in __aexit__ …
```

🐛 Use `uint32` for flush count packing

---

.github/workflows/tests.yml
electrumx/server/block_processor.py
electrumx/server/history.py
electrumx/server/http_middleware.py
electrumx/server/http_session.py
electrumx/server/session.py
electrumx_server
tests/server/test_compaction.py

The purpose of this release includes:
- Fixes `LOG_LEVEL` case-insensitive behavior. https://github.com/atomicals/atomicals-electrumx/pull/173
- Adds `blockchain.atomicals.get_block_hash` handler to obtain the specific block hash from height. https://github.com/atomicals/atomicals-electrumx/pull/174
- Fixes `params` parsing in HTTP session when it's omitted. https://github.com/atomicals/atomicals-electrumx/pull/175
- Improves the flush count to avoid overflow by increasing the range from `2^16` (`uint16`) to `2^32` (`uint32`). https://github.com/atomicals/atomicals-electrumx/pull/176
- Adds semaphore for chain reorg action. https://github.com/atomicals/atomicals-electrumx/pull/177
- Adds socket session request logs and unifies HTTP session request logs. …

Patch Release: v1.4.1

---

electrumx/lib/coins.py
electrumx/server/block_processor.py
electrumx/server/daemon.py
electrumx/server/db.py
electrumx/server/env.py
electrumx/server/http_session.py
electrumx/server/mempool.py
electrumx/server/session.py

1. Fix payments recognition during advances (#180)
2. Improve transaction operations (#181)

Patch release: 1.4.2

---

electrumx/lib/atomicals_blueprint_builder.py
electrumx/lib/util_atomicals.py
electrumx/server/http_session.py
tests/lib/test_atomicals_blueprint_builder.py

Define a "z" op, for custom color outputs.
Payload like this:
```
operation_found_at_inputs["payload"] = {
"9527efa43262636d8f5917fc763fbdd09333e4b387afd6d4ed7a905a127b27b4i0": {
"0": 200,
"1": 300,
},
"8888e25790cc118773c8590522e1cab2ccc073a9375b238aaf9aadb13a764a13i0": {
"2": 8000,
"4": 8000,
}
}
``` 
We can set any int in every outputs. and custom colored ft.
Be careful, If your payload is flawed, it may lead to unnecessary burned.

Custom colored

---

electrumx/server/session.py

```
WARNING:SessionManager:Request <Request POST /proxy/blockchain.atomicals.transaction > has failed with exception: TypeError("AtomicalsTransferBlueprintBuilder.__init__() missing 1 required positional argument: 'is_custom_coloring_activated'")
WARNING:SessionManager:Traceback (most recent call last):
File "/Users/skywalker/atomicals-electrumx/electrumx/server/http_middleware.py", line 61, in middleware_handler
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/Users/skywalker/atomicals-electrumx/electrumx/server/http_middleware.py", line 115, in middleware_handler
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/Users/skywalker/atomicals-electrumx/electrumx/server/http_session.py", line 1792, in atomicals_transaction
return await …
```

Fix blockchain.atomicals.transaction bug

---

electrumx/lib/atomicals_blueprint_builder.py
tests/lib/test_atomicals_blueprint_builder.py

Set z payload index from str to int. both all can pass and custom color. int will better.
```
payload = {
"6787f39b5d2fc020eb0f8e68cd925f297065c5c82c86d175cce1a9beaa411239i0": {
1: 546
}
}
```
```
payload = {
"6787f39b5d2fc020eb0f8e68cd925f297065c5c82c86d175cce1a9beaa411239i0": {
"1": 546
}
}
```
Both payloads are compatible with custom colored operations.

Fix z op payload

---

electrumx/server/block_processor.py
electrumx/server/session/session_manager.py

Refactor `make_transfer_inputs` and `make_transfer_outputs` function.
```
if blueprint_builder.ft_atomicals and atomicals_spent_at_inputs:
if not operation_type and not op_raw:
op_raw = "transfer"
for atomical_id, input_ft in blueprint_builder.ft_atomicals.items():
compact_atomical_id = location_id_bytes_to_compact(atomical_id)
res["transfers"]["inputs"] = await make_transfer_inputs(tx.inputs, compact_atomical_id, input_ft, "FT")
for k, v in blueprint_builder.ft_output_blueprint.outputs.items():
res["transfers"]["outputs"] = make_transfer_outputs(k, v)
if blueprint_builder.nft_atomicals and atomicals_spent_at_inputs:
if not operation_type and not op_raw:
op_raw = "transfer"
for atomical_id, input_nft in blueprint_builder.nft_atomicals.items():
compact_atomical_id = …
```

Fix transaction inputs outputs calculation error.

---

.gitignore
electrumx/server/session/http_session.py

Electrumx Version: 1.5.0.1
After synced with current height:
1. `/prxoy` throw `HttpSession.proxy() takes 1 positional argument but 2 were given`
2. `/proxy/health` throw `Object of type Response is not JSON serializable`

fix `/proxy` and `/proxy/health` response

---

electrumx/server/db.py

Indexer should display `atomical value` in holders API, Instead of utxo value.

Fix holder value error

---

electrumx/lib/atomicals_blueprint_builder.py
electrumx/lib/util_atomicals.py
electrumx/server/block_processor.py

1. `circulating_supply` must use atomcal-value, not utxo value,
2. fix custom color payload: payload must be safely convert to int, it can't be float. *If it cannot be correctly converted to an integer, it will be assigned a value of 0.*

Fix `circulating_supply` ValueError, and fix custom color payload

---

pyproject.toml

Revert build-system to `setuptools`, otherwise we can't use `setup.py` to include extra packages.

fix: wrong build system
